sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
before_install:
  - npm install -g hexo-cli
install:
  - npm install
branches:
  only:
    - hexoProject # build master branch only
script:
  - hexo clean
  - hexo generate
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: hexoProject
  local-dir: public
notifications:
  email:
    - 604135528@qq.com
  on_success: change
  on_failure: always